# Generated by Django 4.1.7 on 2023-03-27 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cosapp.cosmeticbrand'),
        ),
        migrations.AddField(
            model_name='userreview',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
