# Generated by Django 4.1.7 on 2023-03-27 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0002_product_brandname_userreview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='userreview',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
