# Generated by Django 4.1.7 on 2023-04-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0003_remove_userreview_rating_userreview_stars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cosmeticbrand',
            old_name='companyName',
            new_name='cosmeticCompany',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='typeName',
            new_name='productType',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='cateName',
            new_name='productCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brandName',
        ),
        migrations.AddField(
            model_name='product',
            name='cosmeticBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosapp.cosmeticbrand'),
            preserve_default=False,
        ),
    ]
