# Generated by Django 4.1.7 on 2023-04-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0005_alter_product_numreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
