# Generated by Django 4.1.7 on 2023-04-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0006_alter_userreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
