# Generated by Django 4.2.16 on 2024-11-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cosapp", "0008_alter_userreview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cosapp.productcategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="avgRating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="numReviews",
            field=models.IntegerField(default=0),
        ),
    ]
